variables:
- group: anaconda

jobs:
- template: azure-pipelines-template.yml
  parameters:
    platforms:
    - name: linux
      image: ubuntu-16.04
    - name: macos
      image: macos-10.13
    - name: windows
      image: vs2017-win2016
    packages:
    - name: yt
      repo: https://github.com/yt-project/yt.git
      branch: master
      label: dev
    python_versions:
    - 3.7
    - 3.6
    - 2.7
