jobs:
- template: azure-pipelines-template.yml
  parameters:
    platforms:
    - os: linux
      image: ubuntu-16.04
      source_cmd: source
    - os: macos
      image: macos-10.13
      source_cmd: source
    - os: windows
      image: vs2017-win2016
      source_cmd: call
    packages:
    - yt
    python_versions:
    - 3.7
    - 3.6
    - 2.7
